- rust_icu_sys/build.rs
- rust_icu_uloc/src/lib.rs
- `language()`, `script()`, `country()`, `variant()`
- `add_likely_subtags()`, `minimize_subtags()`
Also improve error message in `build.rs`.
> Add several string methods to ULoc

- rust_icu_common/Cargo.toml
- rust_icu_common/src/lib.rs
Use `thiserror` crate, which provides derivations for `std::Error::Error`.
> Migrate from `failure` to `thiserror`

- rust_icu_sys/Cargo.toml
- rust_icu_sys/build.rs
Old build.rs failed with very hermetic and user-unfriendly error
reports, making it hard to debug the root causes of build errors.
Such behavior is unnecessary, and this change improves it.
Fixes #16.
> Improves error handling in build.rs

- rust_icu_common/Cargo.toml
- rust_icu_common/README.md
- rust_icu_sys/README.md
- rust_icu_ucal/Cargo.toml
- rust_icu_ucal/README.md
- rust_icu_udat/Cargo.toml
- rust_icu_udat/README.md
- rust_icu_udata/Cargo.toml
- rust_icu_udata/README.md
- rust_icu_uenum/Cargo.toml
- rust_icu_uenum/README.md
- rust_icu_uloc/Cargo.toml
- rust_icu_uloc/README.md
- rust_icu_ustring/Cargo.toml
- rust_icu_ustring/README.md
- rust_icu_utext/Cargo.toml
- rust_icu_utext/README.md
Contains the changes that were required to make publication work.
- Modifies all `Cargo.toml` files into the form suitable for
publication.
- Adds a README.md file for rust_icu_sys
- Adds a README.md file for rust_icu_common
- Adds a README.md file for rust_icu_uenum
- Adds a README.md file for rust_icu_ustring
- Adds a README.md file for rust_icu_ucal
- Adds a README.md file for rust_icu_udata
- Adds a README.md file for rust_icu_udat and rust_icu_uloc
- Adds a README.md file for rust_icu_utext
Fixes #15
> Prepares rust_icu for publication to `crates.io`.

- rust_icu_common/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_sys/build.rs
- rust_icu_ucal/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
Some environments do not need the `build.rs` smarts.  Allow the users
to skip using build.rs in such environments.
Fixes: #20
> Adds an option to skip icu-config run.

- rust_icu_common/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
This looks as if it may be required for our ability to turn certain
features *off* when compiling for targets that do not require special
settings.
I'm not super-convinced that this is the case, but the only way to
test the theory is to try it out.
> Reexports features throughout.

- rust_icu_common/Cargo.toml
- rust_icu_sys/Cargo.toml
Two repository paths in `Cargo.toml` files incorrectly referred
to subdirectories, instead of top-level repository URLs.
Fixes: #25
> Corrects the repository URLs where wrong.

- rust_icu_common/src/lib.rs
- rust_icu_sys/build.rs
- rust_icu_sys/src/lib.rs
- rust_icu_udata/src/lib.rs
- rust_icu_uenum/src/lib.rs
- rust_icu_uloc/src/lib.rs
- rust_icu_ustring/src/lib.rs
- rust_icu_utext/src/lib.rs
Note that due to a [bug in ICU4C](https://unicode-org.atlassian.net/projects/ICU/issues/ICU-20931), this only accepts exact matches.
> Add wrapper for `uloc_acceptLanguage`

- Makefile
- README.md
- build/Dockerfile.buildenv
- build/Dockerfile.hermetic
- build/Dockerfile.maint-64
- build/Dockerfile.testenv
- build/Makefile
- build/README.md
Adds Docker-based build and tests, for easy start.  Handles
part of issue #31, making it easy to check out the source code and
try the library out.
Documents the details in README.md.
> Adds docker-based build and test processes

- Makefile
The docker container name was wrong; local tests worked because I had
the container with the same name available locally.
> Corrects the name of the docker container

- Makefile
- build/Dockerfile.buildenv
- build/Dockerfile.maint-64
- build/Dockerfile.testenv
- build/Makefile
The new setup:
- runs as the local user (instead of user root)
- mounts host source directory *and* cargo directories, so that any work
done in the container remains usable outside of it.
This setup makes it possible to run tests inside and outside the
container, as the developer chooses to do.
The goal is the ability to run a hermetic set of tests for
different build configurations in a continuous-integration environment.
> Improves the docker build-test setup

- .travis.yml
- Makefile
- README.md
- build/Dockerfile.maint
- build/Dockerfile.testenv
- build/Makefile
- build/entrypoint.sh
This will allow us to run CI builds for each combination of ICU versions
and features.  Issue #38 will be resolved once all environments of
interest are being tested.
> Adds ICU test environments by version

- rust_icu_uloc/src/lib.rs
Also:
- Implement Rust macros for generating wrappers for the numerous `uloc` methods that output strings into a buffer of a fixed size.
> [uloc] Implement `to_language_tag()`

- rust_icu_uloc/src/lib.rs
Fix getters returning long strings of `'\0'` instead of empty strings.
> [uloc] Fix bug in ULoc getters

- Makefile
- README.md
- rust_icu_common/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
I'd like to push this minimal bug fix release, and then make the next release 0.1.0, reflecting the `ULoc` API changes we discussed.
> Increase version to 0.0.6

- rust_icu_common/Cargo.toml
- rust_icu_common/src/lib.rs
- rust_icu_ucal/src/lib.rs
- rust_icu_uenum/src/lib.rs
- rust_icu_uloc/Cargo.toml
- rust_icu_uloc/src/lib.rs
- rust_icu_ustring/src/lib.rs
- `ULoc` traits: `Hash`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`
- `ULoc` methods:
- `keywords`, `keyword_value`, `unicode_keywords`, `unicode_keyword_value`
- `for_language_tag` (factory method)
- Change some getters to return `Option<String>` instead of `Result<String, Error>` with possibly empty strings
- Crate functions:
- `to_unicode_locale_key`
- `to_unicode_locale_type`
- `to_legacy_key`
> [uloc] Implement new methods and standard Rust traits for ULoc

- rust_icu_common/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_sys/build.rs
- rust_icu_sys/src/lib.rs
- rust_icu_ucal/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
Uses the `bindgen` library, instead of a `bindgen` executable
to generate the library bindings.
This helps in issue #41, working towards a set of crates with
documentation that compiles on `docs.rs`.  Also, it places the
responsiblity for bindgen versioning in the hands of cargo, which
is better than needing to have the correct version installed.
> Use `bindgen` library to generate bindings

- README.md
- rust_icu_sys/README.md
- rust_icu_sys/build.rs
icu-config is a deprecated utility and is not available
in linux distributions out of the box.  This prevents
the library from compiling under "default" development
environments.
For details, see issue #41.
> Drop the use of icu-config in favor of pkg-config

- .travis.yml
- README.md
- build/Makefile
Looking into a resolution of issue #41, seems like we'd need
to modify the build environment of `docs.rs` to include the
development ICU library.  Looking at the packages available,
it seems that this is going to have to be ICU version 63.
Hence, adding the build and test envs with ICU 63.  They will be
linked into the build process as a followup.
> Starts testing the library with ICU 63

- build/Makefile
Since ICU 67 has been released, we can start testing for it.  This adds
the facility to build and push ICU 67.
The images will be built and pushed once this makes it into master.
See issue #76.
> Adds the build and test environments for ICU 67

- Makefile
- README.md
- rust_icu_sys/build.rs
- rust_icu_uloc/Cargo.toml
- rust_icu_uloc/build.rs
- rust_icu_uloc/src/lib.rs
With the following changes, we should be well positioned to tackle
ICU 67.1
- ICU4C correctly implements language fallbacks starting version 67.1,
added two flavors of the same test, one for ICU versions 67 and
onwards, and another for older versions.  Feature:
`icu_version_67_plus`.  This happens in issue #59.
- ICU4C version 63 has wrong result for a certain test, possibly due to
the CLDR version on my machine, so test failed.  Turned that test off
for versions less than 64.  This happens on my machine only, when the
system ICU is used.
See also issue #76 for where this is going to start being used.
> Fixes broken test behaviors on old and new ICUs

- .travis.yml
- Makefile
- rust_icu_umsg/src/lib.rs
This is the last step in getting rust_icu tested with ICU 67.1  There
are a few pull requests in flight that preempt this one, such as #75,
but once those are commited, this can go in. (And should pass.)
Fixes #76.
> Starts testing with ICU 67.1

- coverage/report.md
- coverage/ucal_implemented.txt
- coverage/uenum_implemented.txt
- rust_icu_ucal/src/lib.rs
- rust_icu_uenum/src/lib.rs
- rust_icu_uloc/build.rs
- rust_icu_uloc/src/lib.rs
- Add aliases for `uloc` and `ucal` methods that must be kept in `uenum`.
- Mark the versions in `uenum` as `#[doc(hidden)]`.
- Change wrapper of `ucal_openTimeZoneIDEnumeration` to support omitting the region. Add tests.
This CL contains breaking API changes and will require incrementing the minor version.
Fixes #80.
> Add aliases in the proper crates for methods implemented in `uenum`

- .github/workflows/test.yml
- README.md
Starts testing feature sets continuously
Continuous feature testing ensures long-term health of the few feature
combinations that are important to us.
In this change:
- Added Github Actions to test renaming+icu_version_in_env, which is
useful for Fuchsia and ICU uprevs there.  Not running full coverage at
the moment due to combinatorial explosion.  I propose that from here
onwards we test new ICU versions only, i.e. 67 and later.
- Made the compatibility matrix in README.md a bit more compact, to the
extent possible.
- Added instructions on how to build `rust_icu` with a specific feature
set.
Issue: #90
> Starts testing feature sets continuously

- Makefile
Start using buildenv 1.0.0.
(It's high time to promote buildenv to its ~release form).
> Update bindgen script

- rust_icu_ucal/Cargo.toml
- rust_icu_ucal/src/lib.rs
In `rust_icu_ucal`, replace `UDateFormat` parsing with hard-coded timestamps.
Closes #96 with a workaround.
> Remove dev-dependency cycle in ucal

- rust_icu_ucol/Cargo.toml
Build dependencies are only relevant for build.rs, which
is not used in the 'ucol' crate.  They made it into this Cargo.toml
because I had used an existing one as a template and didn't
clean it up properly.
> Removes copy-pastaed build deps from Cargo.toml

- rust_icu_sys/Cargo.toml
This should prevent `bindgen` and its transitive dependencies from being pulled in for non-`bindgen` builds.
> Make bindgen an optional build-dependency

- Makefile
Empirically I noticed that 30s of pause after an upload
is enough for followup uploads to be able to see previously
uploaded code.
Since I prefer to fire a `make publish` and forget over babysitting
the process, I'd opt for the increased timeout.
> Increases the publish timeout to 30s from 5s

- rust_icu_ucol/src/lib.rs
This was detected in a build failure on Fuchsia on arm64.
> Use std::os::raw::c_char instead of hardcoded i8

- .cargo/config
- .github/workflows/test.yml
- Makefile
Buildenv 1.1.0 is hopefully upgraded to do *correct* feature testing.
The answer here seems to be "yes, it's correct", based on spot-checks.
One more issue came up while I was probing: the builds that didn't use
the build script didn't get the appropriate `-L` flag added to the
linker command, and would therefore fail.  I added the .cargo/config
file for that.  While in theory these settings could clash with those
produced by the build.rs, I think in practice this will likely be rare. (You'd
need to have a conflicting version of ICU in /usr/local/lib *and* elsewhere.)
As result, I also restructured the test workflows:
- Broke the tests apart into subsets - now all ICU versions 64 and up
are tested with the flag icu_version_64_plus.
- Removed incompatible flag combinations: `use_bindgen` …
> Start using buildenv 1.1.0

- Makefile
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
Changes below.
commit a602da147595cb1070607c7c5b20129adc987f02
Author: Didrik Nordström <dnordstrom@google.com>
rust_icu_uloc: Make build.rs no-op if icu_config is disabled
commit 6fd6cc17031cbe2dba1e5f4035f3a2b01ca9795a
Author: Filip Filmar <fmil@google.com>
Start using buildenv 1.1.0
commit a209f7e01430c29763d1e7d6fd6f2145591bee07
Author: Filip Filmar <fmil@google.com>
A proposal for a minimal ECMA 402 API surface
commit 6859b7bf72715f9249c0e038be600be7d8bc59af
Author: Filip Filmar <fmil@google.com>
Adds the intro README.md
commit 883b3ea5f9ee8f9d52daa43007a734a0dc48938b
Author: Filip Filmar <fmil@google.com>
Fixes a number of mistakes in the feature setup
commit 355123bbdf04f211900b6f3da50a30925216c777
Author: Filip Filmar <fmil@google.com>
After-the-fact trim-down of excess text …
> Uprev to a version 0.3.0 of rust_icu.

- Cargo.toml
- Makefile
- README.md
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_sys/bindgen/lib_63.rs
- rust_icu_sys/bindgen/lib_64.rs
- rust_icu_sys/bindgen/lib_65.rs
- rust_icu_sys/bindgen/lib_66.rs
- rust_icu_sys/bindgen/lib_67.rs
- rust_icu_sys/bindgen/run_bindgen.sh
- rust_icu_sys/build.rs
- rust_icu_ucal/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uenum/src/lib.rs
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_upluralrules/README.md
- rust_icu_upluralrules/src/lib.rs
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
Adds the support for locale-sensitive plural rules
Plural rules determines what gets printed when one needs to format "1 file"
or "10 files" for human consumption.  Each language may have very own rules
about what number is considered singular, what is considered plural.
Languages have different rules about the numbers subject to the rule, and
even about the number of plurals that are used.
Closes #127
> ICU upluralrules

- ecma402_traits/src/lib.rs
- ecma402_traits/src/listformat.rs
- ecma402_traits/src/pluralrules.rs
- rust_icu_ecma402/Cargo.toml
- rust_icu_ecma402/src/lib.rs
- rust_icu_ecma402/src/listformat.rs
- rust_icu_ecma402/src/pluralrules.rs
Adds the `select` implementation that does not use the formatting hints
from the number formatter.
That's being left for followup work.
> Implements ECMA 402 pluralrules using ICU

- rust_icu_upluralrules/src/lib.rs
- rust_icu_ustring/src/lib.rs
There is a macro buffered_String_method_with_retry which does this
little variable buffer dance that is sometimes needed in the ICU4C
API.  This macro is the same thing, except the end result is not a
UTF8 string, but a UChar string.
This will come in handy in Issue #141, since `unum.h` comes with 
quite a few methods that fit this general pattern.
> Creates a Unicode string macro with retry

- rust_icu_uformattable/src/lib.rs
- rust_icu_unum/Cargo.toml
- rust_icu_unum/src/lib.rs
Part 3 in the unum number formatting support work.
Please see individual commits for details of the change.
Using uformattable::UFormattable provides
generalized value parsing for the particular
locale.
While this isn't the full spectrum of the
underlying functions that ICU4C provides
for value parsing, it's general enough
to be usable for all the use cases where
parsing is needed, *if* needed.  However,
those uses are rare.
Issue #141.
> Unum part 3

- rust_icu_umsg/src/lib.rs
Message formatting must have extern "C" as it uses C variadic args;
but its return type is not FFI clean, and the compiler emits a warning.
As we don't intend to use this function in the FFI context, we don't care
about the warning, and therefore turn it off.
> Turns off the improper C type warning for variadic arg.

- ecma402_traits/Cargo.toml
- ecma402_traits/src/lib.rs
- ecma402_traits/src/numberformat.rs
`Intl.NumberFormat` is an ECMA402 API for formatting numbers, number with
units or with currencies based on international settings in CLDR.
Closes #150.
> [ecma402] Proposes a Rust API for NumberFormat

- Makefile
As we've moved Fuchsia to ICU 67, we may as well bump the version
up here.
Ideally, we'd keep this close to the newest supported ICU library
version.  We kept this on 64 to match Fuchsia; now this is no
longer needed.
> Start using ICU 67 as default for docker tests

- build/Dockerfile.buildenv
This should allow us to accept https://github.com/google/rust_icu/pull/158
(Will still need to update the `USED_BUILDENV_VERSION` in the `Makefile`)
> Use rust:1.45 as installation base

- Makefile
This starts using a newer nightly Rust toolchain (1.47)
which, in turn, can compile paste-1.0.0 from pull
request: #158
> Start using buildenv-1.3.0

- ecma402_traits/src/collator.rs
- ecma402_traits/src/lib.rs
This is a common trait implementation for the ECMA402 `Intl.Collator`
object.
Fixes: #162
> Implements ECMA402 Collator traits

- .github/workflows/test.yml
- README.md
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_uloc/src/lib.rs
- rust_icu_umsg/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
This removes the need for every use of `rust_icu_uloc` to
depend on `ecma420_traits` if the marker implementation of
`ecma402_traits::Locale` is not in fact being used.
This happens for example when you are using `rust_icu`
directly and not through any ECMA402 compatible API. This change
should, for example, remove the need for Fuchsia code base to
vendor ecma402_traits.
Closes #171.
> Makes ecma402_traits an optional dependency

- ecma402_traits/src/collator.rs
A typo caused several warning messages, removing.
> Removes documentation warnings

- .github/workflows/test.yml
- Makefile
- README.md
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_ecma402/src/lib.rs
- rust_icu_ecma402/src/listformat.rs
- rust_icu_ecma402/src/numberformat.rs
- rust_icu_ecma402/src/pluralrules.rs
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_uloc/src/lib.rs
- rust_icu_umsg/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
In retrospect, the introduction of the feature was unnecessary.  Instead
of requiring upstream libraries to implement marker interfaces, the
implementation is lifted into the ECMA402 implementation.
This allows rust_icu to continue being independent of ECMA402 traits,
while we're still able to build ECMA402 compatible APIs on top.
> Remove dep on ecma402

- ecma402_traits/src/datetimeformat.rs
- ecma402_traits/src/lib.rs
> Implements the ECMA402 trait for Intl.DateTimeFormat.

- Makefile
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
This change will allow us to release version 0.4.1, which officially supports ICU 68.1
> Release 0.4.1

- ecma402_traits/src/datetimeformat.rs
- rust_icu_common/src/lib.rs
- rust_icu_ecma402/src/lib.rs
- rust_icu_sys/src/lib.rs
- rust_icu_ubrk/src/lib.rs
- rust_icu_ucol/src/lib.rs
- rust_icu_udat/src/lib.rs
- rust_icu_uformattable/src/lib.rs
- rust_icu_uloc/src/lib.rs
- rust_icu_umsg/src/lib.rs
- rust_icu_unumberformatter/src/lib.rs
- rust_icu_ustring/src/lib.rs
- rust_icu_utrans/src/lib.rs
Let's standardize the formatting to make new contributions easier.
For example, https://github.com/google/rust_icu/pull/187 would be
made smaller and would lose incidental formatting changes.
> fix: run `cargo fmt` at the top of the tree

- README.md
- rust_icu_common/src/lib.rs
- rust_icu_sys/build.rs
- rust_icu_ucal/src/lib.rs
- rust_icu_udat/build.rs
- rust_icu_uenum/src/lib.rs
- rust_icu_uloc/build.rs
- rust_icu_umsg/src/lib.rs
- rust_icu_ustring/src/lib.rs
This PR allows `rust_icu` to compile using stable Rust by removing the unused `#![feature(try_trait)]` attributes in the `build.rs`s. I also fixed a couple Clippy warnings there and documented the dependency on Clang (I didn't have Clang installed and compilation failed as it couldn't find `stddef.h`.
> Compile on stable

- ecma402_traits/src/displaynames.rs
- ecma402_traits/src/lib.rs
This completes the set of trait definitions for ECMA402 as per the current
standard.
Fixes #185
> Defines the ECMA402 trait Intl.DisplayNames

- Makefile
- rust_icu_sys/build.rs
Modifies `build.rs` to use the include directory as output by
`pkg-config --cppflags` instead of just the install prefix.
It seems as if this doesn't matter but there are distributions
that take creative liberties with the directory layout and that
confused the old code.
The new code uses the list of include directories, and verifies that
the needed header files are in fact available on the file system
during `build.rs` execution.
See #189
> build: makes include dirs more precise

- ecma402_traits/src/datetimeformat.rs
- rust_icu_common/src/lib.rs
- rust_icu_ecma402/Cargo.toml
- rust_icu_ecma402/src/datetimeformat.rs
- rust_icu_ecma402/src/lib.rs
- rust_icu_udat/src/lib.rs
- rust_icu_uloc/src/lib.rs
I realized that, in order to initialize the date-time formatter
propertly, I will need to admit changes to a once-defined locale.
So, adding the code that does that.
See: #135
> Changes in preparation for implementing Intl.DateTimeFormat.

- build/entrypoint.sh
It turns out that it is no longer allowed to install without --force if binaries are already there.
Apparently, `--force` will allow it.
Tested locally:
```
git tag -a 1.4.2-rc1
(cd build && make)
env USED_BUILDENV_VERSION=1.4.2-rc1 RUST_ICU_MAJOR_VERSOIN_NUMBER=69 \
make docker-test
```
Issue #198
> Add --force to buildenvs

- Makefile
- ecma402_traits/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_ecma402/src/datetimeformat.rs
- rust_icu_ecma402/src/listformat.rs
- rust_icu_ecma402/src/pluralrules.rs
- rust_icu_udat/src/lib.rs
- rust_icu_uloc/src/lib.rs
- rust_icu_unum/src/lib.rs
Handles a few hopefully minor bitrot items that I noticed while adding
support for ICU 96 in issue #198.
Pulling that rug uncovered issue #203 too.
Fixed: #202
> ICU v96 touch-ups.

- rust_icu_ecma402/src/datetimeformat.rs
The date time format test didn't have a time zone chosen.
This meant that the date time formatting was done based
on the local time zone, which can vary across machines.
I didn't catch this originally because I worked on a
machine that was in UTC, just the same as the machines
which were running the tests.
> Deflake the date time format test

- README.md
Emphasize the docker build flow a bit more. This is the fastest
way to get going with rust_icu.
> Updates the quickstart instructions

- ecma402_traits/Cargo.toml
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_utrans/Cargo.toml
This change removes the extraneous warnings from the Cargo.toml files
which accummulated but wre never removed. I realized that they are
printed on every cargo invocation, which makes for a lot of unneded
output.
So, removed.
> Remove compile warnings stemming from Cargo.toml.

- rust_icu_sys/src/lib.rs
The warning comes about because `bindgen` chooses to use an UB idiom to
generate tests. There is nothing that `rust_icu` can reasonably do about
it.  But since `bindgen` folks are interested in resolving the issue, we
can hope that future `bindgen` versions will resolve the issue.
In the meantime, let's not pollute the (already verbose) build output with
these warnings.
See: https://github.com/rust-lang/rust-bindgen/issues/1651 for details.
> Suppress nullptr dereference warning in rust_icu_sys/src/lib.rs.

- rust_icu_sys/build.rs
- rust_icu_sys/src/lib.rs
Earlier versions of cargo insisted on running comments generated
from C++ code as rust tests when the comment lines were indented.
This is of course not correct behavior for generated code. Since at
the time there was no way to turn the behavior off, we had to turn
off documentation generation.
Now that the behavior seems to be implemented, we can start
generating docs again.
> Adopts the C++ comments from the ICU library

- Makefile
- rust_icu_uchar/Cargo.toml
Broke the target `publish` into a few smaller targets and added the correct
dependencies between those targets.
This removes a certain class of errors from publishing crates in the wrong
order.  The approach could be continued to its logical conclusion, but for
the time being I opted not to do that.
> Use make dependency tracking for some crate publications

- README.md
The markdown link references were malformed.  This fixes the issue.
> Fixes the links to docker and git in README.md

- rust_icu_uchar/src/lib.rs
- rust_icu_unum/src/lib.rs
- rust_icu_unumberformatter/src/lib.rs
These prevented rust_icu from being compilable with the stable rust
toolchain.  It seems that the features are unused at the moment, or
have melded into the more recent stable toolchain versions.
Issue: #225
> Remove the (unused) features

- rust_icu_ucal/src/lib.rs
Starting from ICU 70, the time zone data version can have more than a
single letter after the release number. We used to have versions like
`2020a`, `2020b` etc.  With ICU 70, we get `2021a1`.
We're adopting the same regex as in:
https://fuchsia-review.googlesource.com/c/fuchsia/+/597898
for quick checks of the version string.
Fixes: #221
> Adjust the time zone data regex

- .github/workflows/test.yml
- Makefile
- README.md
- ecma402_traits/Cargo.toml
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_uchar/Cargo.toml
- rust_icu_ucnv/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_unorm2/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
The uprev to 2.0.0 is due to the drop for support of ICU 67 and
the introduction of ICU 70.
Issue #223
> Uprev rust_icu to 2.0.0

- Makefile
I think at some point I forgot to revert this local change and
accidentally made it a part of a commit.
Fixes #223
> Uncomments the publish target for rust_icu_sys

- rust_icu_ucol/src/lib.rs
The use case is allowing the use of `rust_icu` upstream for fuzzer-based comparison of ICU4X and ICU4C results.
> Wrap ucol_setMaxVariable

- rust_icu_common/src/lib.rs
- rust_icu_ulistformatter/src/lib.rs
- rust_icu_uloc/src/lib.rs
- rust_icu_unorm2/src/lib.rs
- rust_icu_ustring/src/lib.rs
The character conversion code uses a two-pass approach for converting
potentially large inputs into various Unicode strings.  The first
pass uses a fixed capacity buffer (often 200 units).  For strings
that happen to be shorter, the conversion succeeds and nothing else
needs to be done.
But for longer strings, the conversion fails, returning a non-OK status
and the size of the buffer that is actually needed.  A second pass then
provides a buffer that's exactly long enough.
That's great and all, but `status` is reused across both calls, and when
the conversion fails, `status` needs to be set back to `OK_CODE` before
the 2nd pass is attempted.
Props for having the assertion that checks for this; but boos for not
actually testing the conversion code with long strings.
Fixes: #244
> Fix the buffer preflight treatment and add tests

- rust_icu_sys/build.rs
Hiya,
It seems `rust_icu` doesn't build when the path to ICU contains the string `-l`, such as when it's in `~/my-libs/icu`. This is because we run `pkg-config --libs icu-i18n` to get the linker flags, and we `str::replace` on it to turn `-Lpath` into `-L path` (to [placate Cargo](https://github.com/rust-lang/cargo/issues/7217)):
```rust
/// Obtains the needed flags for the linker.
fn ldflags(&mut self) -> Result<String> {
// Replacements needed because of https://github.com/rust-lang/cargo/issues/7217
let result = self
.rep
.run(&["--libs", "icu-i18n"])
.with_context(|| "could not get the ld flags")?;
Ok(result.replace("-L", "-L ").replace("-l", "-l "))
}
```
https://github.com/rust-lang/cargo/issues/7217 was fixed in https://github.com/rust-lang/cargo/commit/cfdf00ea9dd2ed25c65da83641eb6 …
> Allow -l and -L in the path where ICU is installed

- rust_icu_common/src/lib.rs
- rust_icu_uformattable/src/lib.rs
- rust_icu_unum/src/lib.rs
- rust_icu_unumberformatter/src/lib.rs
Metavars don’t work in doc comments, as can be seen on docs.rs on [methods like this one](https://docs.rs/rust_icu_ucol/latest/rust_icu_ucol/struct.UCollator.html#method.set_max_variable). This can be fixed by using a manual `#[doc]` attribute with `concat!` and `stringify!`,
> Fix use of metavars in doc comments

- rust_icu_sys/build.rs
The macro here mistakenly uses double braces, which make the compiler complain.
> Fix build.rs for when renaming is off.

- rust_icu_common/src/lib.rs
- rust_icu_uloc/src/lib.rs
It is far simpler if this macro is just a function that accepts a closure.
> Implement `buffered_string_method_with_retry` as a function

- rust_icu_common/src/lib.rs
- rust_icu_common/tests/hygiene.rs
Small PR that builds on #251 to make `simple_drop_impl!` hygienic as well. Only see the last commit, the rest are included in #251.
> Make `simple_drop_impl!` hygienic

- .github/workflows/test.yml
- Makefile
- README.md
- ecma402_traits/Cargo.toml
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_uchar/Cargo.toml
- rust_icu_ucnv/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_unorm2/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
- 3.0.0 brings support for ICU 72.1
- Dropped support for ICU 68.1, and ICU 69.1, they are out of support
window.
- Dropped `rust_icu` 0.5, it is out of support window.
>  Uprev rust_icu to 3.0.0

- Makefile
- build/Dockerfile.buildenv
- build/Dockerfile.testenv
This handles the issue with some dependencies dropping support for older rust versions.
See https://github.com/google/rust_icu/pull/274 for details.
Issue: #276
> Update buildenv to rust 1.71.0

- .github/workflows/test.yml
This might allow us to catch bitrot issues early.
Bitrot is fixed in https://github.com/google/rust_icu/pull/277, so this probably needs to wait until that PR is merged.
> Adds a once-per-week scheduled run for the build

- .github/workflows/test.yml
- Makefile
- rust_icu_sys/bindgen/run_bindgen.sh
Modifies the github workflow to add a static bindgen run.
Lately we had issues with running that command locally and I realized there are no workflows that exercise it.
That's the `make static-bindgen`.
> fixup: Adds a test run for static-bindgen

- Makefile
- ecma402_traits/Cargo.toml
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_uchar/Cargo.toml
- rust_icu_ucnv/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_ucsdet/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_udata/src/lib.rs
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_unorm2/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
This should be a better way to manage the resource memory, as resources created by `open` are memory
mapped on demand.
Some memory-constrained execution environments may care.
> feat: support UDataMemory::open

- Makefile
- ecma402_traits/Cargo.toml
- rust_icu/Cargo.toml
- rust_icu_common/Cargo.toml
- rust_icu_ecma402/Cargo.toml
- rust_icu_intl/Cargo.toml
- rust_icu_sys/Cargo.toml
- rust_icu_ubrk/Cargo.toml
- rust_icu_ucal/Cargo.toml
- rust_icu_uchar/Cargo.toml
- rust_icu_ucnv/Cargo.toml
- rust_icu_ucol/Cargo.toml
- rust_icu_ucsdet/Cargo.toml
- rust_icu_udat/Cargo.toml
- rust_icu_udata/Cargo.toml
- rust_icu_udata/src/lib.rs
- rust_icu_uenum/Cargo.toml
- rust_icu_uformattable/Cargo.toml
- rust_icu_ulistformatter/Cargo.toml
- rust_icu_uloc/Cargo.toml
- rust_icu_umsg/Cargo.toml
- rust_icu_unorm2/Cargo.toml
- rust_icu_unum/Cargo.toml
- rust_icu_unumberformatter/Cargo.toml
- rust_icu_upluralrules/Cargo.toml
- rust_icu_ustring/Cargo.toml
- rust_icu_utext/Cargo.toml
- rust_icu_utrans/Cargo.toml
The implementation of UDataMemory via NonNull prevented using
UDataMemory in threaded contexts. Now, in general this is correct.
But in our case, there is no other way to use the data in threaded
context except through the C++ library which requires holding a pointer.
So...
Issue: #282
> Fixup sync send

- rust_icu_ucsdet/src/lib.rs
Fixes the build of `rust_icu_ucsdet` for Android targets, since `c_char` is defined a `*const u8`.
```
error[E0308]: mismatched types
--> external/crate_index__rust_icu_ucsdet-4.2.3/src/lib.rs:90:17
|
88 |             versioned_function!(ucsdet_setText)(
|             ----------------------------------- arguments to this function are incorrect
89 |                 self.rep.as_ptr(),
90 |                 text.as_ptr() as *const i8,
|                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*const i8`
|
= note: expected raw pointer `*const u8`
found raw pointer `*const i8`
```
> fix: use *const c_char cast instead of *const i8

- rust_icu_sys/src/lib.rs
- rust_icu_uchar/src/lib.rs
- rust_icu_ucnv/src/lib.rs
- rust_icu_ucnv/src/utf8.rs
- rust_icu_ucol/src/lib.rs
- rust_icu_udat/src/lib.rs
- rust_icu_uenum/src/lib.rs
- rust_icu_uformattable/src/lib.rs
- rust_icu_ulistformatter/src/lib.rs
- rust_icu_uloc/src/lib.rs
- rust_icu_unorm2/src/lib.rs
- rust_icu_unum/src/lib.rs
- rust_icu_unumberformatter/src/lib.rs
Remove statements which, for some reason, caused older compiler versions to error out.
This doesn't seem to be the case now, and there should be no reason to keep them.
> chore: remove statements causing warnings

- rust_icu_sys/src/lib.rs
On Apple systems, `libc++` is the default C++ library[^1]. Trying to compile a binary example using `rust_icu` with the `static` feature enabled will currently fail on Apple systems with the following error:
```
= note: ld: library 'stdc++' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This patch links against `libc++` on Apple and FreeBSD systems when the `static` features is enabled.
Note: maybe adding a CI job that builds on macOS in `static` mode is also a good idea?
[^1]: https://developer.apple.com/xcode/cpp/
> Link against libc++ on Apple targets

- .github/workflows/test.yml
- Makefile
- README.md
- rust_icu_sys/build.rs
- rust_icu_sys/src/lib.rs
While using `rust_icu` with Bazel, I realized that the `#[cfg_attr]` attributes in the code make everything difficult.
This brings the following improvement:
- Makes it easier to add combination of features to change the flags, since we can use proper branching
- Moving the instructions to the `build.rs` enables building `rust_icu` with Bazel (which can skip using the `build.rs` file)
- Adds the ability to specify the `RUST_ICU_LINK_SEARCH_DIR` environment variable when you need to use a non-installed build of `icu4c`
- Document the `static` feature and add a CI job to test this for both Ubuntu and macOS
> Move linking flags to build.rs to help with non-cargo build systems

- build/showprogress.sh
- coverage/report.md
- coverage/udat_implemented.txt
- coverage/udata_implemented.txt
- coverage/uenum_implemented.txt
- coverage/uloc_implemented.txt
- coverage/umsg_implemented.txt
- coverage/unumberformatter_implemented.txt
- coverage/ustring_implemented.txt
- coverage/utext_implemented.txt
- rust_icu_uenum/src/lib.rs
- rust_icu_uloc/src/lib.rs
- Ignore trailing '()' characters in function names when reporting coverage.
- Only track functions that match a function in the header file of interest as implemented.
- Mark the uenum::uloc_open_keywords as deprecated, copy the implementation into the uloc crate and copy the test that was in the     uloc crate into the uenum crate so that it is still protected by a test even though deprecated.
> fix: Improve the accuracy of the coverage report.

- build/Dockerfile.buildenv
- build/Makefile
I remembered that buildenv often bitrots. It might be a good idea to give it a quick check once in a while.
> fix: adds a test runner for buildenv

- rust_icu_sys/Cargo.toml
Building in a Fedora 41 container againts clang-19 results in a lib.rs (output from bindgen) that is missing key functions like u_strFromUTF8.
Digging deeper, this is a problem with bindgen, see <https://github.com/rust-lang/rust-bindgen/issues/2945>.
Update bindgen to a newer version which is just new enough to fix the problem.
Fixes <https://github.com/google/rust_icu/issues/305>.
> rust_icu_sys: fix build with clang-19

- .cargo/config
- .cargo/config.toml
- .github/workflows/main.yaml
- Makefile
- build/Dockerfile.buildenv
- build/Dockerfile.maint
- build/Dockerfile.testenv.current
- build/Makefile
- build/README.md
- build/entrypoint-test-current.sh
For the longest time, we had no way to run tests of rust_icu
against top-of-tree ICU. This meant that if a build break was
in the works upstream, we would not know until the release.
This change fixes the issue. We now maintain a "current" environment
which will download and build ICU from `main` before running tests.
Also a small fix: 
- fix: the config file extension is not required to be .toml
> feat: create a container for building ICU against main

- .github/workflows/test.yml
- Makefile
This starts using the new "build rust_icu with `main` ICU branch" test workflow.and carefully at that
It does take a long time to complete, some 10 minutes. It builds ICU from `main` sequentially due to hitting memory issues otherwise. But the build seems to complete with success, and this is what we wanted.
> chore: release a new buildenv, and a new workflow
