google/rust_icu

rust_icu_sys/build.rs
The new code is able to print somewhat nicer diagnostics.  Also,
grouped the commands on `icu-config` into an `impl`, to clean
the script up a bit conceptually.
=> Cleans up the command invocation a bit

rust_icu_common/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_ucal/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_udata/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_ustring/Cargo.toml, rust_icu_utext/Cargo.toml
This will perhaps allow us to import the library in Fuchsia
and override the feature set as we need to.
=> Overrides the default feature set everywhere.

Makefile, build/Dockerfile.testenv
Adds targets `publish` and `uprev` to be used for
publication and uprevving the versions of the crates.
=> Adds some handy tools for publishing

Makefile
In case `make docker-test` is ran with sudo, we need to recover
the original user environment for `docker-test` run to complete
with success.
This commit modifies the determination of the current directory,
UID, GID, username and $HOME dir, so that this works well.
Tested:
`sudo make docker-test`
`make clean`
Fixes #46
=> Fixes user determination for sudo runs.

README.md, docs/README.md, docs/releasing.md
The processes are a bit simplistic at the moment, but they work.
A little bit of know-how is needed, and it's better to document it than
to rely on code spelunking to figure out.
Fixes #49
=> Documents the release processes

Cargo.toml, Makefile, rust_icu_common/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_sys/build.rs, rust_icu_ucal/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_umsg/Cargo.toml, rust_icu_umsg/README.md, rust_icu_umsg/src/lib.rs, rust_icu_ustring/Cargo.toml, rust_icu_ustring/src/lib.rs, rust_icu_utext/Cargo.toml
Slated for v0.1.1 since this is a backward-compatible API.
Fixes: 56
=> Adds support for basic message formatting.

Makefile, rust_icu_umsg/Cargo.toml
One of these days I will stop forgetting thins.
=> Forgot to uprev `umsg`

Makefile, README.md, rust_icu_common/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_ucal/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_udata/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_umsg/Cargo.toml, rust_icu_ustring/Cargo.toml, rust_icu_utext/Cargo.toml
A patch release that should test whether it is now
possible to compile in docs.rs.
=> Releases v0.1.2

Cargo.toml, Makefile, README.md, rust_icu_intl/Cargo.toml, rust_icu_intl/README.md, rust_icu_intl/src/lib.rs, rust_icu_umsg/src/lib.rs
The implementation is minimal since it leans quite a bit onto the
existing ICU functionality.
=> Implements ECMA-402-ish PluralRules.

README.md
I forgot to finish off the paragraph, now fixed.
While I'm there, I added some more guidelines
around building and testing.
=> Finish the `cargo test` paragraph.

Makefile
Makes the `make test` call a bit more ergonomic.
=> Fixes the `make test` target.

coverage/report.md, coverage/ucal_implemented.txt, coverage/uloc_all.txt, rust_icu_ucal/Cargo.toml, rust_icu_ucal/src/lib.rs
=> Implement time zone methods in UCalendar

rust_icu_sys/bindgen/lib_66.rs, rust_icu_sys/bindgen/lib_67.rs
Here's how to update (and that's now documented in README.md):
```
make static-bindgen
```
Seems to be much easier to do than a set of obscure instructions.  Though you need to know about the specific make target.
Fixes: #89
=> Update static bindgens.

rust_icu_sys/Cargo.toml, rust_icu_sys/build.rs
Gates `bindgen` dependency and all uses of `bindgen` behind the `use-bindgen` feature.
=> Make bindgen an optional build-dependency; make build.rs feature-gated

rust_icu_uloc/Cargo.toml, rust_icu_uloc/build.rs
Also, clarify documentation in `uloc`'s build.rs.
=> Remove bindgen dependency from `uloc`

experimental/README.md, experimental/ecma402_listformat/Cargo.toml, experimental/ecma402_listformat/src/lib.rs
=> Ecma402 traits

ecma402_traits/src/pluralrules.rs
=> Adds a trait definition for Intl.PluralRules.

ecma402_traits/src/numberformat.rs, rust_icu_ecma402/Cargo.toml, rust_icu_ecma402/src/lib.rs, rust_icu_ecma402/src/numberformat.rs, rust_icu_unumberformatter/src/lib.rs
Implements ECMA402 `Intl.NumberFormat` in terms of `rust_icu` and `unumberformat`.
Closes #152
=> Ecma402 icu impl

coverage/report.md, coverage/ucol_implemented.txt, coverage/unum_implemented.txt, rust_icu_common/src/lib.rs, rust_icu_ucol/src/lib.rs, rust_icu_unum/src/lib.rs
Attribute setting will be used in the ECMA402 collator implementation
options.
Issue: #162
=> Adds attribute setting to the ICU collator

rust_icu_udat/src/lib.rs
=> Fix tests icu 68.1

.github/workflows/test.yml, README.md, docs/releasing.md, ecma402_traits/src/listformat.rs, proposals/ecma402_listformat/src/lib.rs, rust_icu/Cargo.toml, rust_icu_common/Cargo.toml, rust_icu_common/src/lib.rs, rust_icu_ecma402/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_ubrk/Cargo.toml, rust_icu_ucal/Cargo.toml, rust_icu_ucol/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_udata/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uformattable/Cargo.toml, rust_icu_ulistformatter/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_umsg/Cargo.toml, rust_icu_unum/Cargo.toml, rust_icu_unumberformatter/Cargo.toml, rust_icu_upluralrules/Cargo.toml, rust_icu_utext/Cargo.toml, rust_icu_utrans/Cargo.toml
Where possible, replaces contentious word use with recommended alternatives.
=> Respectful code modifications

rust_icu_ucol/src/lib.rs
By adding a safe wrapper around ucol_getSortKey().
=> collation: add sort key support

Makefile, README.md, ecma402_traits/Cargo.toml, rust_icu/Cargo.toml, rust_icu_common/Cargo.toml, rust_icu_ecma402/Cargo.toml, rust_icu_intl/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_ubrk/Cargo.toml, rust_icu_ucal/Cargo.toml, rust_icu_ucol/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_udata/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uformattable/Cargo.toml, rust_icu_ulistformatter/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_umsg/Cargo.toml, rust_icu_unum/Cargo.toml, rust_icu_unumberformatter/Cargo.toml, rust_icu_upluralrules/Cargo.toml, rust_icu_ustring/Cargo.toml, rust_icu_utext/Cargo.toml, rust_icu_utrans/Cargo.toml
Ahead of a 1.0.1 release.
https://github.com/google/rust_icu/pull/208 may care too.
=> Update readme versioning

Makefile, ecma402_traits/Cargo.toml, rust_icu/Cargo.toml, rust_icu_common/Cargo.toml, rust_icu_ecma402/Cargo.toml, rust_icu_intl/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_ubrk/Cargo.toml, rust_icu_ucal/Cargo.toml, rust_icu_ucol/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_udata/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uformattable/Cargo.toml, rust_icu_ulistformatter/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_umsg/Cargo.toml, rust_icu_unorm2/Cargo.toml, rust_icu_unum/Cargo.toml, rust_icu_unumberformatter/Cargo.toml, rust_icu_upluralrules/Cargo.toml, rust_icu_ustring/Cargo.toml, rust_icu_utext/Cargo.toml, rust_icu_utrans/Cargo.toml
Skipping 1.0.2 since I botched its tag.
=> Prepare for an update to 1.0.3

.github/workflows/test.yml
Summary of changes:
- Adds a test fixture for ICU 70.1 in all appropriate configurations.
- Fixes up quotations in `test.yml` for correct formatting.
Issue: #223
=> Modifies the testing workflows to include testing for ICU 70.1

README.md
Updated the support matrix since one of the latest updates
has broken the table formatting.
Fixes: #239
=> Fix the support matrix in README.md

Makefile, ecma402_traits/Cargo.toml, rust_icu/Cargo.toml, rust_icu_common/Cargo.toml, rust_icu_ecma402/Cargo.toml, rust_icu_intl/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_ubrk/Cargo.toml, rust_icu_ucal/Cargo.toml, rust_icu_uchar/Cargo.toml, rust_icu_ucnv/Cargo.toml, rust_icu_ucol/Cargo.toml, rust_icu_udat/Cargo.toml, rust_icu_udata/Cargo.toml, rust_icu_uenum/Cargo.toml, rust_icu_uformattable/Cargo.toml, rust_icu_ulistformatter/Cargo.toml, rust_icu_uloc/Cargo.toml, rust_icu_umsg/Cargo.toml, rust_icu_unorm2/Cargo.toml, rust_icu_unum/Cargo.toml, rust_icu_unumberformatter/Cargo.toml, rust_icu_upluralrules/Cargo.toml, rust_icu_ustring/Cargo.toml, rust_icu_utext/Cargo.toml, rust_icu_utrans/Cargo.toml
This change makes it possible to release the recent bugfixes,
such as #244
=> Uprev the versioning to 2.0.3

coverage/report.md, coverage/ucol_all.txt, coverage/uformattable_implemented.txt, coverage/unum_implemented.txt, coverage/unumberformatter_implemented.txt
Updates the stats about the coverage of wrapped functions.
=> Update the results of the progress script.

rust_icu/Cargo.toml, rust_icu_sys/Cargo.toml, rust_icu_sys/src/lib.rs
This is not the same solution as in #228, but it works perfectly fine for me. Also, note that I’m not too well-versed in linking so I may have made a mistake here.
Closes: #228
=> Add `static` feature flag

coverage/report.md, coverage/udata_implemented.txt, coverage/uloc_implemented.txt, coverage/unum_all.txt, coverage/unumberformatter_all.txt
In the meantime quite a few new functions were implemented, without updating the coverage report. Let's do that now.
=> chore: update the coverage report
